services:
    prototype.event:
        class: Core\PrototypeBundle\Event\Event
        
    prototype_formtype_factory:
        class: Core\PrototypeBundle\Form\FormTypeFactory
        arguments: [@service_container]

    prototype_grid_config_factory:
        class: Core\PrototypeBundle\GridConfig\GridConfigFactory
        arguments: [@service_container]   
           
    prototype.configurator.service:
        class: Core\PrototypeBundle\Service\Configurator
        arguments: [@service_container] 
    
   
    prototype.grid.configurator.service:
        class: Core\PrototypeBundle\Service\GridConfigurator
        arguments: [@service_container] 
   
   
    prototype.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [%prototype_config_params%]        
        tags:
            -  { name: prototype.config }
    
#    prototype.grid.config:
#        class: TMSolution\DataGridBundle\GridBuilder\GridBuilder
#        arguments: [%prototype_config_params%]        
#        tags:
#            -  { name: prototype.grid.config }     
   