parameters:
   
    prototype.association.config.list.parameters:
        twig_base_index: 'CorePrototypeBundle:Association\Base:index.html.twig'
    
   # prototype.association.config.parameters:
      #  twig_element_read: 'CorePrototypeBundle:Association\Element:read.html.twig'
        
      
        
services:

###############################################################
    prototype.grid_controller:
        class: Core\PrototypeBundle\Controller\GridDefaultController
        arguments: [@service_container,@request_stack]
    
################################################################    
    data_collector.prototype:
        class: Core\PrototypeBundle\Profiler\PrototypeCollector
        arguments: []
        tags:
            - { name: data_collector, template: "CorePrototypeBundle:Profiler:collector", id: "prototype" }
    
    prototype.event:
        class: Core\PrototypeBundle\Event\Event
        
    prototype.controler.params:
        class: Core\PrototypeBundle\Service\ControllerParams
        
    prototype_formtype_factory:
        class: Core\PrototypeBundle\Form\FormTypeFactory
        arguments: [@service_container]

    prototype_grid_config_factory:
        class: Core\PrototypeBundle\Config\GridConfigFactory
        arguments: [@service_container]   
           
############################################################    
    prototype.configurator.service:
        class: Core\PrototypeBundle\Service\Configurator
        arguments: [@service_container] 
   
    prototype.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [%prototype_config_params%]        
        tags:
            -  { name: prototype.config }  
############################################################    
    prototype.gridconfig.configurator.service:
        class: Core\PrototypeBundle\Service\GridConfigConfigurator
        arguments: [@service_container] 
    #niezgrabna 
    prototype.gridconfig:
        class: TMSolution\DataGridBundle\GridConfig\GridConfig
        arguments: [@service_container]        
        tags:
            -  { name: prototype.gridconfig }
############################################################    
    prototype.listconfig.configurator.service:
        class: Core\PrototypeBundle\Service\ListConfigConfigurator
        arguments: [@service_container] 
    #niezgrabna 
    prototype.listconfig:
        class: Core\PrototypeBundle\Config\ListConfig
        arguments: [@service_container]        
        tags:
            -  { name: prototype.listconfig }
################################################################
    prototype.viewconfig.configurator.service:
        class: Core\PrototypeBundle\Service\ViewConfigConfigurator
        arguments: [@service_container] 
    #niezgrabna 
    prototype.viewconfig:
        class: Core\PrototypeBundle\Config\ViewConfig
        arguments: [@service_container]        
        tags:
            -  { name: prototype.viewconfig }
################################################################


    prototype.formtype.configurator.service:
        class: Core\PrototypeBundle\Service\FormTypeConfigurator
        arguments: [@service_container] 
    
    prototype.formtype:
        class: Core\PrototypeBundle\Form\FormType
        arguments: []        
        tags:
            -  { name: prototype.formtype }  
################################################################
    prototype.association.list.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [@prototype.config,%prototype.association.config.list.parameters%]        
        tags:
            -  { name: prototype.config, route: core_prototype_associationcontroller_list }
            
    prototype.association.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [@prototype.config]        
        tags:
            -  { name: prototype.config, route: core_prototype_associationcontroller_ }            

            
    prototype.gridconfig.associationgridconfig:
        class: Core\PrototypeBundle\Config\AssociationGridConfig
        arguments: [@service_container]        
        tags:
            -  { name: prototype.gridconfig, route: core_prototype_associationcontroller_ }        
   
    prototype.ajax.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [@prototype.config,%prototype.association.config.list.parameters%]        
        tags:
            -  { name: prototype.config, route: core_prototype_ajaxcontroller_ }



    prototype.twig_extension:
        class: Core\PrototypeBundle\Twig\UcWordsExtension
        public: true
        tags:
            - { name: twig.extension }

    prototype.container_aware_type:
        class: Core\PrototypeBundle\Form\ContainerAwareType
        calls:
          - [setContainer, ['@service_container']]
        tags:
            - { name: form.type, alias: 'container_aware' }