parameters:
    prototype.association.config.params: 
          twig_element_read: 'CorePrototypeBundle:Association\Element:read.html.twig'

services:
    prototype.event:
        class: Core\PrototypeBundle\Event\Event
        
    prototype.controler.params:
        class: Core\PrototypeBundle\Service\ControllerParams
        
    prototype_formtype_factory:
        class: Core\PrototypeBundle\Form\FormTypeFactory
        arguments: [@service_container]

    prototype_grid_config_factory:
        class: Core\PrototypeBundle\GridConfig\GridConfigFactory
        arguments: [@service_container]   
           
    prototype.configurator.service:
        class: Core\PrototypeBundle\Service\Configurator
        arguments: [@service_container] 
    
   
    prototype.grid.configurator.service:
        class: Core\PrototypeBundle\Service\GridConfigurator
        arguments: [@service_container] 
   
   
    prototype.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [%prototype_config_params%]        
        tags:
            -  { name: prototype.config }
    
  
    prototype.association.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [%prototype_config_params%,%prototype.association.config.params%]        
        tags:
            -  { name: prototype.config, route: core_prototype_associationcontroller_* }
            
    prototype.association.gridconfig:
        class: Core\PrototypeBundle\GridConfig\AssciationGridConfig
        arguments: [%prototype_config_params%,%prototype.association.config.params%]        
        tags:
            -  { name: prototype.config, route: core_prototype_associationcontroller_* }        
   