parameters:
   
    prototype.association.config.list.parameters:
        twig_base_index: 'CorePrototypeBundle:Association\Base:index.html.twig'
    
   # prototype.association.config.parameters:
      #  twig_element_read: 'CorePrototypeBundle:Association\Element:read.html.twig'
        
      
        
services:
    
    data_collector.prototype:
        class: Core\PrototypeBundle\Profiler\PrototypeCollector
        arguments: []
        tags:
            - { name: data_collector, template: "CorePrototypeBundle:Profiler:collector", id: "prototype" }
    
    prototype.event:
        class: Core\PrototypeBundle\Event\Event
        
    prototype.controler.params:
        class: Core\PrototypeBundle\Service\ControllerParams
        
    prototype_formtype_factory:
        class: Core\PrototypeBundle\Form\FormTypeFactory
        arguments: [@service_container]

    prototype_grid_config_factory:
        class: Core\PrototypeBundle\Config\GridConfigFactory
        arguments: [@service_container]   
           
############################################################    
    prototype.configurator.service:
        class: Core\PrototypeBundle\Service\Configurator
        arguments: [@service_container] 
   
    prototype.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [%prototype_config_params%]        
        tags:
            -  { name: prototype.config }  
############################################################    
    prototype..configurator.service:
        class: Core\PrototypeBundle\Service\GridConfigConfigurator
        arguments: [@service_container] 
    #niezgrabna 
    prototype.gridconfig:
        class: TMSolution\DataGridBundle\GridConfig\GridConfig
        arguments: [%prototype_config_params%]        
        tags:
            -  { name: prototype.gridconfig }
################################################################               
    prototype.formtype.configurator.service:
        class: Core\PrototypeBundle\Service\FormTypeConfigurator
        arguments: [@service_container] 
    
    prototype.formtype:
        class: Core\PrototypeBundle\Form\FormType
        arguments: []        
        tags:
            -  { name: prototype.formtype }  
################################################################
    prototype.association.list.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [@prototype.config,%prototype.association.config.list.parameters%]        
        tags:
            -  { name: prototype.config, route: core_prototype_associationcontroller_list }
            
    prototype.association.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [@prototype.config]        
        tags:
            -  { name: prototype.config, route: core_prototype_associationcontroller_ }            

            
    prototype.gridconfig.associationgridconfig:
        class: Core\PrototypeBundle\Config\AssociationGridConfig
        arguments: [@service_container]        
        tags:
            -  { name: prototype.gridconfig, route: core_prototype_associationcontroller_ }        
   
    prototype.ajax.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [@prototype.config,%prototype.association.config.list.parameters%]        
        tags:
            -  { name: prototype.config, route: core_prototype_ajaxcontroller_ }