services:
    prototype.classmapperservice:
        class: "Core\PrototypeBundle\Service\ClassMapper"
        arguments: ["@service_container","%objectMapper%"]
        
    prototype.eventlistener.classmapper:
      class: Core\BaseBundle\EventListener\ClassMapperListener
      arguments: [@service_container]
      tags:
         - { name: kernel.event_listener, priority: 61, event: kernel.controller, method: onKernelController}
                  
