parameters:
   

services:
    prototype.event:
        class: Core\PrototypeBundle\Event\Event
        
    prototype.controler.params:
        class: Core\PrototypeBundle\Service\ControllerParams
        
    prototype_formtype_factory:
        class: Core\PrototypeBundle\Form\FormTypeFactory
        arguments: [@service_container]

    prototype_grid_config_factory:
        class: Core\PrototypeBundle\GridConfig\GridConfigFactory
        arguments: [@service_container]   
           
    prototype.configurator.service:
        class: Core\PrototypeBundle\Service\Configurator
        arguments: [@service_container] 
    
   
    prototype.gridbuilder.configurator.service:
        class: Core\PrototypeBundle\Service\GridBuilderConfigurator
        arguments: [@service_container] 
   
   
    prototype.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [%prototype_config_params%]        
        tags:
            -  { name: prototype.config }
    
    prototype.gridbuilder:
        class: TMSolution\DataGridBundle\GridBuilder\GridBuilder
        arguments: [%prototype_config_params%]        
        tags:
            -  { name: prototype.gridbuilder }
    
  
  
    prototype.association.config:
        class: Core\PrototypeBundle\Service\Config
        arguments: [%prototype_config_params%]        
        tags:
            -  { name: prototype.config, route: core_prototype_associationcontroller_ }
            
    prototype.gridconfig.associationgridbuilder:
        class: Core\PrototypeBundle\GridConfig\AssociationGridConfig
        arguments: [@service_container]        
        tags:
            -  { name: prototype.gridbuilder, route: core_prototype_associationcontroller_ }        
   