sudo: false

env:

language: php

php:
  - 5.4
  - 5.6
  - 7.0
  - nightly

before_install:

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source

before_script:

script:
  - ./vendor/bin/php-cs-fixer fix
  - ./vendor/bin/phpunit
  - ./vendor/bin/phploc src

after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy:
