cco_user:
    resource: "@CCOUserBundle/Resources/config/routing.yml"
    prefix:   /


core_prototype:
    resource: "@CorePrototypeBundle/Resources/config/routing.yml"
    prefix:   /
    
    
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   / 
    
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
    



hwi_oauth_redirect:
    resource: "@CCOUserBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect


hwi_oauth_connect:
    resource: "@CCOUserBundle/Resources/config/routing/connect.xml"
    prefix: /login



facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    