

services:
    
    prototype.gridconfig.new:
        class: 'AppBundle\GridConfig\ProductCategory'
        arguments: [@service_container]        
        tags:
            -  { name: prototype.gridbuilder, entity: 'AppBundle\Entity\ProductCategory' } 
               
    prototype.gridconfig.product:
        class: 'AppBundle\GridConfig\Product'
        arguments: [@service_container]        
        tags:
            -  { name: prototype.gridbuilder, entity: 'AppBundle\Entity\Product' } 
   
    app.config.nazwa_controllera23:
        class: Core\PrototypeBundle\Service\Config
        arguments: [%prototype_config_params%,{ twig_container_read: "AppBundle:ProductCategory\Container:read.html.twig"}]        
        tags:
            -  { name: prototype.config, entity: 'AppBundle\Entity\ProductCategory'  }    

#    app.config.nazwa_controllera231:
#        class: Core\PrototypeBundle\Service\Config
#        arguments: [%prototype_config_params%,%prototype.association.config.parameters%]        
#        tags:
#            -  { name: prototype.config, route: core_prototype_associationcontroller_read , entity: 'AppBundle\Entity\Product'  }         
        
         #danvbe/UserBundle/Resources/services.yml
