#swieta nazwa - nie wolno jej zmieniać PO CO TO?
core_prototype_ajaxcontroller_list:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/list/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/lista/{states}" } 
    defaults: { _controller: "prototype.grid_controller:listAction", states: "", _format: ~ }
    requirements: { "containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
        
#swieta nazwa - nie wolno jej zmieniać PO CO TO?
core_prototype_ajaxcontroller_ajaxlist:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/ajaxlist/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/listaajax/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxlistAction", states: "", _format: ~ }
    requirements: { "containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true    
        
#swieta nazwa - nie wolno jej zmieniać PO CO TO?
core_prototype_ajaxcontroller_grid:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/grid/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/grid/{states}" } 
    defaults: { _controller: "prototype.grid_controller:gridAction", states: "", _format: ~ }
    requirements: { "containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
        
#swieta nazwa - nie wolno jej zmieniać PO CO TO?
core_prototype_ajaxcontroller_ajaxgrid:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/ajaxgrid/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/gridajax/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxgridAction", states: "", _format: ~ }
    requirements: { "containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true            
       
#swieta nazwa - nie wolno jej zmieniać    
core_prototype_ajaxcontroller_read:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/read/{id}/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/pobierz/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:readAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true

#### widoki tworzące obiekt
#święta nazwa - nie wolno jej zmieniać    
core_prototype_ajaxcontroller_new:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/new/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/nowy/{states}"}
    defaults: { _controller: "prototype.grid_controller:newAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
#swieta nazwa - nie wolno jej zmieniać
core_prototype_ajaxcontroller_create:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/create/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/utworz/{states}" }
    defaults: { _controller: "prototype.grid_controller:createAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true       
#święta nazwa - nie wolno jej zmieniać    
core_prototype_ajaxcontroller_delete:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/delete/{id}/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/usun/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:deleteAction", states: "", _format: ~ }       
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
#### widoki aktualizujące obiekt
#święta nazwa - nie wolno jej zmieniać - update    
core_prototype_ajaxcontroller_edit:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/edit/{id}/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/edytuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:editAction", states: "", _format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true    
#święta nazwa - nie wolno jej zmieniać    
core_prototype_ajaxcontroller_update:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/update/{id}/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/aktualizuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:updateAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
        
core_prototype_ajaxcontroller_view:
    locales:  { en: "/ajax/{entityName}/{containerName}/{actionId}/view/{id}/{states}", pl: "/ajax/{entityName}/{containerName}/{actionId}/podglad/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:viewAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true 