core_prototype_api_associationcontroller_list:
    locales:  { en: "/{entityName}/{prefix}/list/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/lista/{parentName}/{parentId}/{states}" } 
    defaults: { _controller: "prototype.grid_controller:listAction", states: "", _format: ~ }
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_api_associationcontroller_ajaxlist:
    locales:  { en: "/{entityName}/{prefix}/ajaxlist/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/listaajax/{parentName}/{parentId}/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxlistAction", states: "", _format: ~ }
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_api_associationcontroller_grid:
    locales:  { en: "/{entityName}/{prefix}/grid/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/grid/{parentName}/{parentId}/{states}" } 
    defaults: { _controller: "prototype.grid_controller:gridAction", states: "", _format: ~ }
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_api_associationcontroller_ajaxgrid:
    locales:  { en: "/{entityName}/{prefix}/ajaxgrid/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/gridajax/{parentName}/{parentId}/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxgridAction", states: "", _format: ~ }
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_api_associationcontroller_read:
    locales:  { en: "/{entityName}/{prefix}/read/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/pokaz/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:readAction", states: "", _format: ~ } 
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true    

core_prototype_api_associationcontroller_new:
    locales:  { en: "/{entityName}/{prefix}/new/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/nowy/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:newAction", states: "", _format: ~ }   
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true

core_prototype_api_associationcontroller_create:
    locales:  { en: "/{entityName}/{prefix}/create/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/utworz/{parentName}/{parentId}/{states}" }
    defaults: { _controller: "prototype.grid_controller:createAction", states: "", _format: ~ }   
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true       

core_prototype_api_associationcontroller_delete:
    locales:  { en: "/{entityName}/{prefix}/delete/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/usun/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:deleteAction", states: "", _format: ~ }       
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true

core_prototype_api_associationcontroller_edit:
    locales:  { en: "/{entityName}/{prefix}/edit/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/edytuj/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:editAction", states: "", _format: ~ }
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_api_associationcontroller_update:
    locales:  { en: "/{entityName}/{prefix}/update/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/aktualizuj/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:updateAction", states: "", _format: ~ }   
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true

core_prototype_api_associationcontroller_view:
    locales:  { en: "/{entityName}/{prefix}/view/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{prefix}/podglad/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:viewAction", states: "", _format: ~ }   
    requirements: {  "states": ".+", "parentId": "\d+" }
    options:
        expose: true   