
core_prototype_api_defaultcontroller_list:
    locales:  { en: "/{entityName}/{actionId}/list/{states}", pl: "/{entityName}/{actionId}/lista/{states}" } 
    defaults: { _controller: "prototype.grid_controller:listAction", states: "", format: ~ }
    requirements: {  "states": ".+"}
    options:
        expose: true
        

core_prototype_api_defaultcontroller_ajaxlist:
    locales:  { en: "/{entityName}/{actionId}/ajaxlist/{states}", pl: "/{entityName}/{actionId}/listaajax/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxlistAction", states: "", format: ~ }
    options:
        expose: true   
        
core_prototype_api_defaultcontroller_grid:
    locales:  { en: "/{entityName}/{actionId}/list/{states}", pl: "/{entityName}/{actionId}/lista/{states}" } 
    defaults: { _controller: "prototype.grid_controller:listAction", states: "", format: ~ }
    requirements: {  "states": ".+"}
    options:
        expose: true
        

core_prototype_api_defaultcontroller_ajaxgrid:
    locales:  { en: "/{entityName}/{actionId}/ajaxgrid/{states}", pl: "/{entityName}/{actionId}/ajaxgrid/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxgridAction", states: "", format: ~ }
    options:
        expose: true   
   
core_prototype_api_defaultcontroller_read:
    locales:  { en: "/{entityName}/{actionId}/read/{id}/{states}", pl: "/{entityName}/{actionId}/pokaz/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:readAction", states: "", format: ~ }   
    requirements: {  "states": ".+"}
    options:
        expose: true


core_prototype_api_defaultcontroller_new:
    locales:  { en: "/{entityName}/{actionId}/new/{states}", pl: "/{entityName}/{actionId}/nowy/{states}"}
    defaults: { _controller: "prototype.grid_controller:newAction", states: "", format: ~ }   
    requirements: {  "states": ".+"}
    options:
        expose: true

core_prototype_api_defaultcontroller_create:
    locales:  { en: "/{entityName}/{actionId}/create/{states}", pl: "/{entityName}/{actionId}/utworz/{states}" }
    defaults: { _controller: "prototype.grid_controller:createAction", states: "", format: ~ }   
    requirements: {  "states": ".+"}
    options:
        expose: true       

core_prototype_api_defaultcontroller_delete:
    locales:  { en: "/{entityName}/{actionId}/delete/{id}/{states}", pl: "/{entityName}/{actionId}/usun/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:deleteAction", states: "", format: ~ }       
    requirements: {  "states": ".+"}
    options:
        expose: true

core_prototype_api_defaultcontroller_edit:
    locales:  { en: "/{entityName}/{actionId}/edit/{id}/{states}", pl: "/{entityName}/{actionId}/edytuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:editAction", states: "", format: ~ }
    requirements: {  "states": ".+"}
    options:
        expose: true    
        
core_prototype_api_defaultcontroller_update:
    locales:  { en: "/{entityName}/{actionId}/update/{id}/{states}", pl: "/{entityName}/{actionId}/aktualizuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:updateAction", states: "", format: ~ }   
    requirements: {  "states": ".+"}
    options:
        expose: true
        
core_prototype_api_defaultcontroller_view:
    locales:  { en: "/{entityName}/{actionId}/view/{id}/{states}", pl: "/{entityName}/{actionId}/podglad/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:viewAction", states: "", format: ~ }   
    requirements: {  "states": ".+"}
    options:
        expose: true        