core_prototype_associationcontroller_list:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/list/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/lista/{parentName}/{parentId}/{states}" } 
    defaults: { _controller: "prototype.grid_controller:listAction", states: "", _format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_associationcontroller_ajaxlist:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/ajaxlist/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/listaajax/{parentName}/{parentId}/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxlistAction", states: "", _format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_associationcontroller_grid:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/grid/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/grid/{parentName}/{parentId}/{states}" } 
    defaults: { _controller: "prototype.grid_controller:gridAction", states: "", _format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_associationcontroller_ajaxgrid:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/ajaxgrid/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/ajaxgrid/{parentName}/{parentId}/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxgridAction", states: "", _format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_associationcontroller_read:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/read/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/pokaz/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:readAction", states: "", _format: ~ } 
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true    

core_prototype_associationcontroller_new:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/new/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/nowy/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:newAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true

core_prototype_associationcontroller_create:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/create/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/utworz/{parentName}/{parentId}/{states}" }
    defaults: { _controller: "prototype.grid_controller:createAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true       

core_prototype_associationcontroller_delete:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/delete/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/usun/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:deleteAction", states: "", _format: ~ }       
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true

core_prototype_associationcontroller_edit:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/edit/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/edytuj/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:editAction", states: "", _format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true
        
core_prototype_associationcontroller_update:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/update/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/aktualizuj/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:updateAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true

core_prototype_associationcontroller_view:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/view/{id}/{parentName}/{parentId}/{states}", pl: "/{entityName}/{containerName}/{prefix}/podglad/{id}/{parentName}/{parentId}/{states}"}
    defaults: { _controller: "prototype.grid_controller:viewAction", states: "", _format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+", "parentId": "\d+" }
    options:
        expose: true