
base_assoc_subprefix-list:
    locales:  { en: "{subPrefix}/{entityPath}/list/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/lista/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:listAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
 
  
base_assoc_subprefix-ajaxlist:
    locales:  { en: "{subPrefix}/{entityPath}/ajaxlist/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/listaajax/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:ajaxlistAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    options:
        expose: true   
        
base_assoc_subprefix-grid:
    locales:  { en: "{subPrefix}/{entityPath}/grid/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/grid/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:gridAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
  

base_assoc_subprefix-ajaxgrid:
    locales:  { en: "{subPrefix}/{entityPath}/ajaxgrid/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/listagrid/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:ajaxgridAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    options:
        expose: true   
   
base_assoc_subprefix-read:
    locales:  { en: "{subPrefix}/{entityPath}/read/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/pokaz/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:readAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true


base_assoc_subprefix-new:
    locales:  { en: "{subPrefix}/{entityPath}/new/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/nowy/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:newAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true

base_assoc_subprefix-create:
    locales:  { en: "{subPrefix}/{entityPath}/create/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/utworz/{parentName}/{parentId}/{state}" }
    defaults: { _controller: "prototype.default_controller:createAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true       

base_assoc_subprefix-delete:
    locales:  { en: "{subPrefix}/{entityPath}/delete/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/usun/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:deleteAction", state: "", format: ~,"containerName": "container", prefix: "system" }       
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true

base_assoc_subprefix-edit:
    locales:  { en: "{subPrefix}/{entityPath}/edit/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/edytuj/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:editAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true    
        
base_assoc_subprefix-update:
    locales:  { en: "{subPrefix}/{entityPath}/update/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/aktualizuj/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:updateAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
        
base_assoc_subprefix-view:
    locales:  { en: "{subPrefix}/{entityPath}/view/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityPath}/podglad/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:viewAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true  
        
        
#####################################

base_assoc-list:
    locales:  { en: "{entityPath}/list/{parentName}/{parentId}/{state}", pl: "/{entityPath}/lista/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:listAction", state: "", "containerName": "container",  format: ~ , prefix: "system"}
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
  

base_assoc-ajaxlist:
    locales:  { en: "{entityPath}/ajaxlist/{parentName}/{parentId}/{state}", pl: "/{entityPath}/listaajax/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:ajaxlistAction", state: "", "containerName": "container",  format: ~ , prefix: "system"}
    options:
        expose: true   
        
base_assoc-grid:
    locales:  { en: "{entityPath}/grid/{parentName}/{parentId}/{state}", pl: "/{entityPath}/grid/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:gridAction", state: "", "containerName": "container",  format: ~, prefix: "system" }
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
  

base_assoc-ajaxgrid:
    locales:  { en: "{entityPath}/ajaxgrid/{parentName}/{parentId}/{state}", pl: "/{entityPath}/listagrid/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:ajaxgridAction", state: "", "containerName": "container",  format: ~ , prefix: "system"}
    options:
        expose: true   
   
base_assoc-read:
    locales:  { en: "{entityPath}/read/{id}/{parentName}/{parentId}/{state}", pl: "/{entityPath}/pokaz/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:readAction", state: "", "containerName": "container",  format: ~, prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true


base_assoc-new:
    locales:  { en: "{entityPath}/new/{parentName}/{parentId}/{state}", pl: "/{entityPath}/nowy/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:newAction", state: "",  "containerName": "container",  format: ~ , prefix: "system"}   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true

base_assoc-create:
    locales:  { en: "{entityPath}/create/{parentName}/{parentId}/{state}", pl: "/{entityPath}/utworz/{parentName}/{parentId}/{state}" }
    defaults: { _controller: "prototype.default_controller:createAction", state: "",  "containerName": "container",   format: ~ , prefix: "system"}   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true       

base_assoc-delete:
    locales:  { en: "{entityPath}/delete/{id}/{parentName}/{parentId}/{state}", pl: "/{entityPath}/usun/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:deleteAction", state: "", "containerName": "container",   format: ~, prefix: "system" }       
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true

base_assoc-edit:
    locales:  { en: "{entityPath}/edit/{id}/{parentName}/{parentId}/{state}", pl: "/{entityPath}/edytuj/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:editAction", state: "", "containerName": "container",   format: ~ , prefix: "system"}
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true    
        
base_assoc-update:
    locales:  { en: "{entityPath}/update/{id}/{parentName}/{parentId}/{state}", pl: "/{entityPath}/aktualizuj/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:updateAction", state: "", "containerName": "container",   format: ~ , prefix: "system"}   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
        
base_assoc-view:
    locales:  { en: "{entityPath}/view/{id}/{parentName}/{parentId}/{state}", pl: "/{entityPath}/podglad/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:viewAction", state: "", "containerName": "container",  format: ~ , prefix: "system"}   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true 
#########################################################
