
base_assoc_subprefix-list:
    locales:  { en: "{subPrefix}/{entityName}/list/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/lista/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:listAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
 
  
base_assoc_subprefix-ajaxlist:
    locales:  { en: "{subPrefix}/{entityName}/ajaxlist/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/listaajax/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:ajaxlistAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    options:
        expose: true   
        
base_assoc_subprefix-grid:
    locales:  { en: "{subPrefix}/{entityName}/grid/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/grid/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:gridAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
  

base_assoc_subprefix-ajaxgrid:
    locales:  { en: "{subPrefix}/{entityName}/ajaxgrid/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/listagrid/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:ajaxgridAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    options:
        expose: true   
   
base_assoc_subprefix-read:
    locales:  { en: "{subPrefix}/{entityName}/read/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/pokaz/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:readAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true


base_assoc_subprefix-new:
    locales:  { en: "{subPrefix}/{entityName}/new/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/nowy/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:newAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true

base_assoc_subprefix-create:
    locales:  { en: "{subPrefix}/{entityName}/create/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/utworz/{parentName}/{parentId}/{state}" }
    defaults: { _controller: "prototype.default_controller:createAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true       

base_assoc_subprefix-delete:
    locales:  { en: "{subPrefix}/{entityName}/delete/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/usun/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:deleteAction", state: "", format: ~,"containerName": "container", prefix: "system" }       
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true

base_assoc_subprefix-edit:
    locales:  { en: "{subPrefix}/{entityName}/edit/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/edytuj/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:editAction", state: "", format: ~,"containerName": "container", prefix: "system" }
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true    
        
base_assoc_subprefix-update:
    locales:  { en: "{subPrefix}/{entityName}/update/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/aktualizuj/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:updateAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
        
base_assoc_subprefix-view:
    locales:  { en: "{subPrefix}/{entityName}/view/{id}/{parentName}/{parentId}/{state}", pl: "{subPrefix}/{entityName}/podglad/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:viewAction", state: "", format: ~,"containerName": "container", prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true  
        
        
#####################################

base_assoc-list:
    locales:  { en: "{entityName}/list/{parentName}/{parentId}/{state}", pl: "/{entityName}/lista/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:listAction", state: "", "containerName": "container",  format: ~ , prefix: "system"}
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
  

base_assoc-ajaxlist:
    locales:  { en: "{entityName}/ajaxlist/{parentName}/{parentId}/{state}", pl: "/{entityName}/listaajax/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:ajaxlistAction", state: "", "containerName": "container",  format: ~ , prefix: "system"}
    options:
        expose: true   
        
base_assoc-grid:
    locales:  { en: "{entityName}/grid/{parentName}/{parentId}/{state}", pl: "/{entityName}/grid/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:gridAction", state: "", "containerName": "container",  format: ~, prefix: "system" }
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
  

base_assoc-ajaxgrid:
    locales:  { en: "{entityName}/ajaxgrid/{parentName}/{parentId}/{state}", pl: "/{entityName}/listagrid/{parentName}/{parentId}/{state}" } 
    defaults: { _controller: "prototype.default_controller:ajaxgridAction", state: "", "containerName": "container",  format: ~ , prefix: "system"}
    options:
        expose: true   
   
base_assoc-read:
    locales:  { en: "{entityName}/read/{id}/{parentName}/{parentId}/{state}", pl: "/{entityName}/pokaz/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:readAction", state: "", "containerName": "container",  format: ~, prefix: "system" }   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true


base_assoc-new:
    locales:  { en: "{entityName}/new/{parentName}/{parentId}/{state}", pl: "/{entityName}/nowy/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:newAction", state: "",  "containerName": "container",  format: ~ , prefix: "system"}   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true

base_assoc-create:
    locales:  { en: "{entityName}/create/{parentName}/{parentId}/{state}", pl: "/{entityName}/utworz/{parentName}/{parentId}/{state}" }
    defaults: { _controller: "prototype.default_controller:createAction", state: "",  "containerName": "container",   format: ~ , prefix: "system"}   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true       

base_assoc-delete:
    locales:  { en: "{entityName}/delete/{id}/{parentName}/{parentId}/{state}", pl: "/{entityName}/usun/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:deleteAction", state: "", "containerName": "container",   format: ~, prefix: "system" }       
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true

base_assoc-edit:
    locales:  { en: "{entityName}/edit/{id}/{parentName}/{parentId}/{state}", pl: "/{entityName}/edytuj/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:editAction", state: "", "containerName": "container",   format: ~ , prefix: "system"}
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true    
        
base_assoc-update:
    locales:  { en: "{entityName}/update/{id}/{parentName}/{parentId}/{state}", pl: "/{entityName}/aktualizuj/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:updateAction", state: "", "containerName": "container",   format: ~ , prefix: "system"}   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true
        
base_assoc-view:
    locales:  { en: "{entityName}/view/{id}/{parentName}/{parentId}/{state}", pl: "/{entityName}/podglad/{id}/{parentName}/{parentId}/{state}"}
    defaults: { _controller: "prototype.default_controller:viewAction", state: "", "containerName": "container",  format: ~ , prefix: "system"}   
    requirements: {"containerName": main|container|element ,  "state": ".+","parentName": ".+","parentId": "\d*"}
    options:
        expose: true 
#########################################################
