
core_prototype_defaultcontroller_list:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/list/{states}", pl: "/{entityName}/{containerName}/{prefix}/lista/{states}" } 
    defaults: { _controller: "prototype.grid_controller:listAction", states: "", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
  

core_prototype_defaultcontroller_ajaxlist:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/ajaxlist/{states}", pl: "/{entityName}/{containerName}/{prefix}/listaajax/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxlistAction", states: "", format: ~ }
    options:
        expose: true   
        
core_prototype_defaultcontroller_grid:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/grid/{states}", pl: "/{entityName}/{containerName}/{prefix}/grid/{states}" } 
    defaults: { _controller: "prototype.grid_controller:gridAction", states: "", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
  

core_prototype_defaultcontroller_ajaxgrid:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/ajaxgrid/{states}", pl: "/{entityName}/{containerName}/{prefix}/listagrid/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxgridAction", states: "", format: ~ }
    options:
        expose: true   
   
core_prototype_defaultcontroller_read:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/read/{id}/{states}", pl: "/{entityName}/{containerName}/{prefix}/pokaz/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:readAction", states: "", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true


core_prototype_defaultcontroller_new:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/new/{states}", pl: "/{entityName}/{containerName}/{prefix}/nowy/{states}"}
    defaults: { _controller: "prototype.grid_controller:newAction", states: "", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true

core_prototype_defaultcontroller_create:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/create/{states}", pl: "/{entityName}/{containerName}/{prefix}/utworz/{states}" }
    defaults: { _controller: "prototype.grid_controller:createAction", states: "", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true       

core_prototype_defaultcontroller_delete:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/delete/{id}/{states}", pl: "/{entityName}/{containerName}/{prefix}/usun/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:deleteAction", states: "", format: ~ }       
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true

core_prototype_defaultcontroller_edit:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/edit/{id}/{states}", pl: "/{entityName}/{containerName}/{prefix}/edytuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:editAction", states: "", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true    
        
core_prototype_defaultcontroller_update:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/update/{id}/{states}", pl: "/{entityName}/{containerName}/{prefix}/aktualizuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:updateAction", states: "", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
        
core_prototype_defaultcontroller_view:
    locales:  { en: "/{entityName}/{containerName}/{prefix}/view/{id}/{states}", pl: "/{entityName}/{containerName}/{prefix}/podglad/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:viewAction", states: "", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true  
        
        
#####################################

core_prototype_defaultcontroller_simplelist:
    locales:  { en: "/{entityName}/list/{states}", pl: "/{entityName}/lista/{states}" } 
    defaults: { _controller: "prototype.grid_controller:listAction", states: "", "containerName": "container", "prefix": "default", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
  

core_prototype_defaultcontroller_simpleajaxlist:
    locales:  { en: "/{entityName}/ajaxlist/{states}", pl: "/{entityName}/listaajax/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxlistAction", states: "", "containerName": "container", "prefix": "default", format: ~ }
    options:
        expose: true   
        
core_prototype_defaultcontroller_simplegrid:
    locales:  { en: "/{entityName}/grid/{states}", pl: "/{entityName}/grid/{states}" } 
    defaults: { _controller: "prototype.grid_controller:gridAction", states: "", "containerName": "container", "prefix": "default", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
  

core_prototype_defaultcontroller_simpleajaxgrid:
    locales:  { en: "/{entityName}/ajaxgrid/{states}", pl: "/{entityName}/listagrid/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxgridAction", states: "", "containerName": "container", "prefix": "default", format: ~ }
    options:
        expose: true   
   
core_prototype_defaultcontroller_simpleread:
    locales:  { en: "/{entityName}/read/{id}/{states}", pl: "/{entityName}/pokaz/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:readAction", states: "", "containerName": "container",  "prefix": "default",format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true


core_prototype_defaultcontroller_simplenew:
    locales:  { en: "/{entityName}/new/{states}", pl: "/{entityName}/nowy/{states}"}
    defaults: { _controller: "prototype.grid_controller:newAction", states: "",  "containerName": "container",  "prefix": "default",format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true

core_prototype_defaultcontroller_simplecreate:
    locales:  { en: "/{entityName}/create/{states}", pl: "/{entityName}/utworz/{states}" }
    defaults: { _controller: "prototype.grid_controller:createAction", states: "",  "containerName": "container",  "prefix": "default", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true       

core_prototype_defaultcontroller_simpledelete:
    locales:  { en: "/{entityName}/delete/{id}/{states}", pl: "/{entityName}/usun/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:deleteAction", states: "", "containerName": "container",  "prefix": "default", format: ~ }       
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true

core_prototype_defaultcontroller_simpleedit:
    locales:  { en: "/{entityName}/edit/{id}/{states}", pl: "/{entityName}/edytuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:editAction", states: "", "containerName": "container",  "prefix": "default", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true    
        
core_prototype_defaultcontroller_simpleupdate:
    locales:  { en: "/{entityName}/update/{id}/{states}", pl: "/{entityName}/aktualizuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:updateAction", states: "", "containerName": "container", "prefix": "default",  format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
        
core_prototype_defaultcontroller_simpleview:
    locales:  { en: "/{entityName}/view/{id}/{states}", pl: "/{entityName}/podglad/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:viewAction", states: "", "containerName": "container", "prefix": "default", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true 
#########################################################


core_prototype_defaultcontroller_actionlist:
    locales:  { en: "/{entityName}/{prefix}/list/{states}", pl: "/{entityName}/{prefix}/lista/{states}" } 
    defaults: { _controller: "prototype.grid_controller:listAction", states: "", "containerName": "container", "prefix": "default", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
  

core_prototype_defaultcontroller_actionajaxlist:
    locales:  { en: "/{entityName}/{prefix}/ajaxlist/{states}", pl: "/{entityName}/{prefix}/listaajax/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxlistAction", states: "", "containerName": "container", "prefix": "default", format: ~ }
    options:
        expose: true   
        
core_prototype_defaultcontroller_actiongrid:
    locales:  { en: "/{entityName}/{prefix}/grid/{states}", pl: "/{entityName}/{prefix}/grid/{states}" } 
    defaults: { _controller: "prototype.grid_controller:gridAction", states: "", "containerName": "container", "prefix": "default", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
  

core_prototype_defaultcontroller_actionajaxgrid:
    locales:  { en: "/{entityName}/{prefix}/ajaxgrid/{states}", pl: "/{entityName}/{prefix}/listagrid/{states}" } 
    defaults: { _controller: "prototype.grid_controller:ajaxgridAction", states: "", "containerName": "container", "prefix": "default", format: ~ }
    options:
        expose: true   
   
core_prototype_defaultcontroller_actionread:
    locales:  { en: "/{entityName}/{prefix}/read/{id}/{states}", pl: "/{entityName}/{prefix}/pokaz/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:readAction", states: "", "containerName": "container",  "prefix": "default",format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true


core_prototype_defaultcontroller_actionnew:
    locales:  { en: "/{entityName}/{prefix}/new/{states}", pl: "/{entityName}/{prefix}/nowy/{states}"}
    defaults: { _controller: "prototype.grid_controller:newAction", states: "",  "containerName": "container",  "prefix": "default",format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true

core_prototype_defaultcontroller_actioncreate:
    locales:  { en: "/{entityName}/{prefix}/create/{states}", pl: "/{entityName}/{prefix}/utworz/{states}" }
    defaults: { _controller: "prototype.grid_controller:createAction", states: "",  "containerName": "container",  "prefix": "default", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true       

core_prototype_defaultcontroller_actiondelete:
    locales:  { en: "/{entityName}/{prefix}/delete/{id}/{states}", pl: "/{entityName}/{prefix}/usun/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:deleteAction", states: "", "containerName": "container",  "prefix": "default", format: ~ }       
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true

core_prototype_defaultcontroller_actionedit:
    locales:  { en: "/{entityName}/{prefix}/edit/{id}/{states}", pl: "/{entityName}/{prefix}/edytuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:editAction", states: "", "containerName": "container",  "prefix": "default", format: ~ }
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true    
        
core_prototype_defaultcontroller_actionupdate:
    locales:  { en: "/{entityName}/{prefix}/update/{id}/{states}", pl: "/{entityName}/{prefix}/aktualizuj/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:updateAction", states: "", "containerName": "container", "prefix": "default",  format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true
        
core_prototype_defaultcontroller_actionview:
    locales:  { en: "/{entityName}/{prefix}/view/{id}/{states}", pl: "/{entityName}/{prefix}/podglad/{id}/{states}"}
    defaults: { _controller: "prototype.grid_controller:viewAction", states: "", "containerName": "container", "prefix": "default", format: ~ }   
    requirements: {"containerName": main|container|element ,  "states": ".+"}
    options:
        expose: true 
        
#######################################

