#swieta nazwa - nie wolno jej zmieniać PO CO TO?
core_prototype_defaultcontroller_list:
    locales:  { en: "/{entityName}/list", pl: "/{entityName}/lista" } 
    methods:  [GET]
    defaults: 
         _controller: "CorePrototypeBundle:GridDefault:list"
         

#swieta nazwa - nie wolno jej zmieniać    
core_prototype_defaultcontroller_read:
    locales:  { en: "/{entityName}/read/{id}", pl:"/{entityName}/pobierz/{id}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:read" }   


#### widoki tworzące obiekt
#święta nazwa - nie wolno jej zmieniać    
core_prototype_defaultcontroller_new:
    locales:  { en: "/{entityName}/new", pl:"/{entityName}/nowy"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:new" }   

#swieta nazwa - nie wolno jej zmieniać
core_prototype_defaultcontroller_create:
    locales:  { en: "/{entityName}/create", pl: "/{entityName}/utworz/" }
    defaults: { _controller: "CorePrototypeBundle:GridDefault:create" }   
       
#święta nazwa - nie wolno jej zmieniać    
core_prototype_defaultcontroller_delete:
    locales:  { en: "/{entityName}/delete/{id}", pl:"/{entityName}/usun/{id}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:delete" }       

#### widoki aktualizujące obiekt
#święta nazwa - nie wolno jej zmieniać - update    
core_prototype_defaultcontroller_edit:
    locales:  { en: "/{entityName}/edit/{id}", pl:"/{entityName}/edytuj/{id}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:edit" }
    
#święta nazwa - nie wolno jej zmieniać    
core_prototype_defaultcontroller_update:
    locales:  { en: "/{entityName}/update/{id}", pl:"/{entityName}/aktualizuj/{id}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:update" }   