#swieta nazwa - nie wolno jej zmieniać PO CO TO?
core_prototype_defaultcontroller_list:
    locales:  { en: "/{entityName}/list/{state}", pl: "/{entityName}/lista/{state}" } 
    defaults: { _controller: "CorePrototypeBundle:GridDefault:list", state: "" }
    requirements: {"state": ".+"}
    options:
        expose: true
        
#swieta nazwa - nie wolno jej zmieniać PO CO TO?
core_prototype_defaultcontroller_ajaxlist:
    locales:  { en: "/{entityName}/ajaxlist/{state}", pl: "/{entityName}/listaajax/{state}" } 
    defaults: { _controller: "CorePrototypeBundle:GridDefault:ajaxlist", state: "" }
    options:
        expose: true        
       
#swieta nazwa - nie wolno jej zmieniać    
core_prototype_defaultcontroller_read:
    locales:  { en: "/{entityName}/read/{id}/{state}", pl:"/{entityName}/pobierz/{id}/{state}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:read", state: "" }   
    requirements: {"state": ".+"}
    options:
        expose: true

#### widoki tworzące obiekt
#święta nazwa - nie wolno jej zmieniać    
core_prototype_defaultcontroller_new:
    locales:  { en: "/{entityName}/new/{state}", pl:"/{entityName}/nowy/{state}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:new", state: "" }   
    requirements: {"state": ".+"}
    options:
        expose: true
#swieta nazwa - nie wolno jej zmieniać
core_prototype_defaultcontroller_create:
    locales:  { en: "/{entityName}/create/{state}", pl: "/{entityName}/utworz/{state}" }
    defaults: { _controller: "CorePrototypeBundle:GridDefault:create", state: "" }   
    requirements: {"state": ".+"}
    options:
        expose: true       
#święta nazwa - nie wolno jej zmieniać    
core_prototype_defaultcontroller_delete:
    locales:  { en: "/{entityName}/delete/{id}/{state}", pl:"/{entityName}/usun/{id}/{state}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:delete", state: "" }       
    requirements: {"state": ".+"}
    options:
        expose: true
#### widoki aktualizujące obiekt
#święta nazwa - nie wolno jej zmieniać - update    
core_prototype_defaultcontroller_edit:
    locales:  { en: "/{entityName}/edit/{id}/{state}", pl:"/{entityName}/edytuj/{id}/{state}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:edit", state: "" }
    requirements: {"state": ".+"}
    options:
        expose: true    
#święta nazwa - nie wolno jej zmieniać    
core_prototype_defaultcontroller_update:
    locales:  { en: "/{entityName}/update/{id}/{state}", pl:"/{entityName}/aktualizuj/{id}/{state}"}
    defaults: { _controller: "CorePrototypeBundle:GridDefault:update", state: "" }   
    requirements: {"state": ".+"}
    options:
        expose: true